
# 📘 Part 6: SVD & Matrix Decomposition (Deep Dive)

This notebook explains **Singular Value Decomposition (SVD)** intuitively,
with a strong focus on **Machine Learning applications**.

Follow the workflow: **read → run → modify → practice**.

---



## 1. Why Do We Need SVD?

Eigenvalues work only for **square matrices**.

But in ML:
- Datasets are often **rectangular**
- Rows ≠ Columns

👉 **SVD works for any matrix**.


In [1]:

import numpy as np



## 2. What is SVD?

Any matrix `A` can be decomposed as:

```
A = U Σ Vᵀ
```

Where:
- `U` → left singular vectors
- `Σ` → singular values (importance)
- `Vᵀ` → right singular vectors


In [2]:

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

U, S, Vt = np.linalg.svd(A)

print("U:\n", U)
print("Singular values:", S)
print("Vᵀ:\n", Vt)


U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular values: [9.52551809 0.51430058]
Vᵀ:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]



## 3. Intuition Behind SVD

- `Vᵀ` → rotate input space
- `Σ` → stretch important directions
- `U` → rotate to output space

👉 SVD finds **important patterns**.



## 4. Singular Values = Importance

- Large singular value → important information
- Small singular value → noise / redundancy


In [3]:

print("Singular values (importance):", S)


Singular values (importance): [9.52551809 0.51430058]



## 5. Dimensionality Reduction Using SVD

We can keep only top `k` singular values.

Result:
- Smaller matrix
- Less noise
- Almost same information


In [4]:

# Low-rank approximation
k = 1

U_k = U[:, :k]
S_k = np.diag(S[:k])
Vt_k = Vt[:k, :]

A_approx = U_k @ S_k @ Vt_k

print("Original A:\n", A)
print("Approximated A:\n", A_approx)


Original A:
 [[1 2]
 [3 4]
 [5 6]]
Approximated A:
 [[1.35662819 1.71846235]
 [3.09719707 3.92326845]
 [4.83776596 6.12807454]]



## 6. ML Applications of SVD

- Dimensionality reduction
- Image compression
- Noise removal
- Recommendation systems



## 7. SVD vs Eigen Decomposition

| Eigen | SVD |
|-----|-----|
| Square matrices only | Works for any matrix |
| Can fail for real data | Very stable |
| Theory-heavy | ML-friendly |



## 8. Important ML Insight

> PCA is usually implemented using **SVD**, not eigenvalues.

Why?
- Numerical stability
- Works for all datasets



## 🧪 Practice Questions

1. Why is SVD preferred over eigen-decomposition in ML?
2. What happens if we drop small singular values?
3. How does SVD help in image compression?



## 🧠 Summary

- SVD works for any matrix
- Singular values represent importance
- Dropping small values removes noise
- PCA uses SVD internally
- SVD is core to modern ML systems

---

### ✅ End of Part 6
