
# 📘 Part 2: Matrices (Deep Dive)

This notebook explains **Matrices from scratch** with a focus on **Machine Learning**.
Read the markdown, run the code, and modify values to learn effectively.

---



## 1. What is a Matrix?

A **matrix** is a rectangular arrangement of numbers organized into **rows and columns**.

### In Machine Learning:
- Entire **dataset = matrix**
- Rows represent **data points**
- Columns represent **features**


In [1]:

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Matrix A:")
print(A)
print("Shape:", A.shape)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)



## 2. Shape of a Matrix

Shape is written as:
```
(rows, columns)
```

### ML Tip:
Shape mismatch is the most common error in ML.


In [2]:

print("Number of rows:", A.shape[0])
print("Number of columns:", A.shape[1])


Number of rows: 3
Number of columns: 3



## 3. Matrix Addition

Two matrices can be added only if their shapes are the same.


In [3]:

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("A + B =")
print(A + B)


A + B =
[[10 10 10]
 [10 10 10]
 [10 10 10]]



## 4. Scalar Multiplication

Multiplying a matrix by a scalar scales all elements.


In [4]:

print("2 × A =")
print(2 * A)


2 × A =
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]



## 5. Matrix × Vector (Prediction)

This operation is used to compute predictions in ML models.


In [5]:

X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

w = np.array([0.5, 1.0])

y = X.dot(w)
print("Predictions y:")
print(y)


Predictions y:
[2.5 5.5 8.5]



## 6. Matrix × Matrix

Rule:
(m × n) · (n × p) → (m × p)


In [6]:

M1 = np.array([[1, 2],
               [3, 4]])

M2 = np.array([[2, 0],
               [1, 2]])

print("M1 × M2 =")
print(M1.dot(M2))


M1 × M2 =
[[ 4  4]
 [10  8]]



## 7. Transpose

Transpose swaps rows and columns.


In [7]:

print("Transpose of A:")
print(A.T)


Transpose of A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]



## 8. Identity Matrix

Identity matrix acts like 1 in multiplication.


In [8]:

I = np.eye(3)
print("Identity matrix:")
print(I)
print("A × I =")
print(A.dot(I))


Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A × I =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]



## 9. Inverse Matrix (Conceptual)

Inverse undoes the matrix transformation.


In [9]:

A_small = np.array([[4, 7],
                    [2, 6]])

A_inv = np.linalg.inv(A_small)

print("A_small:")
print(A_small)
print("Inverse of A_small:")
print(A_inv)
print("A_small × A_inv:")
print(A_small.dot(A_inv))


A_small:
[[4 7]
 [2 6]]
Inverse of A_small:
[[ 0.6 -0.7]
 [-0.2  0.4]]
A_small × A_inv:
[[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]



## 🧪 Practice Questions

1. Find the shape of a dataset with 100 rows and 5 features.
2. Multiply a matrix with a vector of compatible shape.
3. Why are matrices ideal for representing datasets?



## 🧠 Summary

- Matrix represents datasets
- Shape matters
- Matrix-vector multiplication gives predictions
- Transpose and inverse are used in training

---

### ✅ End of Part 2
